name: "Deploy to Docker Hub Action"
description: "Deploy to Docker Hub"
inputs:
  context:
    description: Docker context
    required: true
  tags:
    description: Docker tags
    required: true
  build-args:
    default: ""
    description: Docker build args
    required: false

runs:
  using: "composite"
  steps:
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}
