name: Build and push typos-cli docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 0' # Every Monday at 7:00 AM (JST)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo LATEST_DOCKER_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/imunew/typos-cli/tags/ | jq 'first(.results[] | select(.name != "latest")) | .name' | tr -d '"') >> $GITHUB_ENV
          echo LATEST_TYPOS_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/rust-lang/crates.io-index/master/ty/po/typos-cli | jq '.vers' | jq -s | jq 'last(.[])' | tr -d '"') >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Deploy to Docker Hub
        uses: ./.github/actions/deploy-to-docker-hub
        if: env.LATEST_DOCKER_VERSION != env.LATEST_TYPOS_CLI_VERSION
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./typos-cli/
          tags: imunew/typos-cli:latest,imunew/typos-cli:${{ env.LATEST_TYPOS_CLI_VERSION }}
          build-args: TYPOS_CLI_VERSION=${{ env.LATEST_TYPOS_CLI_VERSION }}

      - name: Trust docker images
        uses: ./.github/actions/docker-trust-sign
        if: env.LATEST_DOCKER_VERSION != env.LATEST_TYPOS_CLI_VERSION
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          image-ref-latest: imunew/typos-cli:latest
          image-ref-specific: imunew/typos-cli:${{ env.LATEST_TYPOS_CLI_VERSION }}
          private-key-id: ${{ secrets.DOCKER_PRIVATE_KEY_ID }}
          private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
          private-key-name: ${{ secrets.DOCKER_PRIVATE_KEY_NAME }}
