name: Build and push typos-cli docker image

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'version of typos-cli'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Deploy to Docker Hub
        uses: ./.github/actions/deploy-to-docker-hub
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./typos-cli/
          tags: imunew/typos-cli:latest,imunew/typos-cli:${{ inputs.version }}
          build-args: TYPOS_CLI_VERSION=${{ inputs.version }}
